name: Add_PR_TO_PROJECT

on:
  pull_request:
    types:
      - review_requested
    branches:
      - main

jobs:
  fake-workflow:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Explanation
        run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"
